name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'

env:
  FILENAME: pushJobFile
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: qcastel/github-actions-maven/actions/maven@master
        with:
          maven-repo-server-id: github
          maven-repo-server-username: ${{ secrets.PRIVATE_GITHUB_REPO_USER }}
          maven-repo-server-password: ${{ secrets.PRIVATE_GITHUB_REPO_PASSWORD }}
          maven-args: "clean package"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILENAME }}.zip
          # A file, directory or wildcard pattern that describes what to upload
          path: ./target/${{ env.FILENAME }}.zip